#
# CD Pipeline
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace

  params:
    - name: repo-url
    - name: branch
      default: main
    - name: build-image

  tasks:
    # 1. Clean workspace
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    # 2. Clone repo
    - name: clone
      taskRef:
        name: git-clone
      runAfter:
        - init
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    # 3. Lint (flake8)
    - name: lint
      taskRef:
        name: flake8
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace

    # 4. Tests (nose)
    - name: tests
      taskRef:
        name: nose
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: database_uri
          value: "sqlite:///test.db"
        - name: args
          value: "-v --with-spec --spec-color"

    # 5. Build image
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - lint
        - tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: "$(params.build-image)"
