apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline

spec:
  workspaces:
    - name: pipeline-workspace

  params:
    - name: repo-url
    - name: branch
      default: main
    - name: build-image

  tasks:
    # ---------------- INIT ----------------
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    # ---------------- CLONE ----------------
    - name: clone
      taskRef:
        name: git-clone
      runAfter:
        - init
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      workspaces:
        - name: output
          workspace: pipeline-workspace

    # ---------------- LINT ----------------
    - name: lint
      taskRef:
        name: flake8
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace

    # ---------------- TESTS ----------------
    - name: tests
      taskRef:
        name: nose
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: database_uri
          value: "sqlite:///test.db"
        - name: args
          value: "-v --with-spec --spec-color"

    # ---------------- BUILD ----------------
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - lint
        - tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: "$(params.build-image)"
